/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: YaHei28.c                                             *
* Font:        Œ¢»Ì—≈∫⁄                                              *
* Height:      28                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  28                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: F:\MDK_STM32\2°¢STM32CubeMX\STM32F107VCT6\5°¢LCD\4°¢STemWinœ‘ æ∫∫◊÷--ing\STemWinLibrary522\font\hzk.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontYaHei28;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontYaHei28_4E1A[ 84] = { /* code 4E1A */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _______X,X___XX__,________,
  _______X,X___XX__,________,
  _______X,X___XX__,________,
  _______X,X___XX__,________,
  _XX____X,X___XX__,__XX____,
  _XXX___X,X___XX__,__XX____,
  __XX___X,X___XX__,_XX_____,
  __XX___X,X___XX__,_XX_____,
  __XXX__X,X___XX__,XXX_____,
  ___XX__X,X___XX__,XX______,
  ___XX__X,X___XX__,XX______,
  ____XX_X,X___XX_X,XX______,
  ____X__X,X___XX__,X_______,
  _______X,X___XX__,________,
  _______X,X___XX__,________,
  _______X,X___XX__,________,
  _______X,X___XX__,________,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYaHei28_4EAC[ 84] = { /* code 4EAC */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,_X______,________,
  ________,_XX_____,________,
  ________,_XXX____,________,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  ________,________,________,
  ________,________,________,
  ___XXXXX,XXXXXXXX,XX______,
  ___XX___,________,XX______,
  ___XX___,________,XX______,
  ___XX___,________,XX______,
  ___XX___,________,XX______,
  ___XXXXX,XXXXXXXX,XX______,
  ___XX___,__XX____,XX______,
  ________,__XX____,________,
  _____XX_,__XX__XX,________,
  ___XXX__,__XX___X,XX______,
  __XX____,__XX____,_XXX____,
  XX______,__XX____,___XX___,
  ______XX,XXX_____,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYaHei28_5357[ 84] = { /* code 5357 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,__XX____,________,
  ________,__XX____,________,
  _XXXXXXX,XXXXXXXX,XXXXX___,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  __XXXXXX,XXXXXXXX,XXXX____,
  __XX__XX,______X_,__XX____,
  __XX___X,X____XX_,__XX____,
  __XX____,X___XX__,__XX____,
  __XX_XXX,XXXXXXXX,X_XX____,
  __XX____,__XX____,__XX____,
  __XX____,__XX____,__XX____,
  __XX____,__XX____,__XX____,
  __XX_XXX,XXXXXXXX,X_XX____,
  __XX____,__XX____,__XX____,
  __XX____,__XX____,__XX____,
  __XX____,__XX____,__XX____,
  __XX____,__XX__XX,XXX_____,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYaHei28_5927[ 84] = { /* code 5927 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  XXXXXXXX,XXXXXXXX,XXXX____,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,XXXX____,________,
  ________,XXXX____,________,
  ________,XX_X____,________,
  _______X,X__XX___,________,
  ______XX,____X___,________,
  ______XX,____XX__,________,
  ____XXX_,_____XX_,________,
  ___XX___,______XX,X_______,
  __XX____,________,XX______,
  XX______,________,_XX_____,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYaHei28_5B66[ 84] = { /* code 5B66 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,_X______,X_______,
  ___X____,_XX____X,XX______,
  ___XX___,_XXX___X,X_______,
  ____XX__,__X___XX,________,
  _____X__,______X_,________,
  _XXXXXXX,XXXXXXXX,XXXX____,
  _XX_____,________,__XX____,
  ________,________,__XX____,
  _____XXX,XXXXXXXX,X_______,
  ________,_____XXX,________,
  ________,___XXX__,________,
  ________,__XX____,________,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ______XX,XXX_____,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYaHei28_5DE5[ 84] = { /* code 5DE5 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  __XXXXXX,XXXXXXXX,XXX_____,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  _XXXXXXX,XXXXXXXX,XXXX____,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontYaHei28_CharInfo[6] = {
   {  21,  21,  3, acGUI_FontYaHei28_4E1A } /* code 4E1A */
  ,{  21,  21,  3, acGUI_FontYaHei28_4EAC } /* code 4EAC */
  ,{  21,  21,  3, acGUI_FontYaHei28_5357 } /* code 5357 */
  ,{  21,  21,  3, acGUI_FontYaHei28_5927 } /* code 5927 */
  ,{  21,  21,  3, acGUI_FontYaHei28_5B66 } /* code 5B66 */
  ,{  21,  21,  3, acGUI_FontYaHei28_5DE5 } /* code 5DE5 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei28_Prop6 = {
   0x5DE5 /* first character */
  ,0x5DE5 /* last character  */
  ,&GUI_FontYaHei28_CharInfo[  5] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei28_Prop5 = {
   0x5B66 /* first character */
  ,0x5B66 /* last character  */
  ,&GUI_FontYaHei28_CharInfo[  4] /* address of first character */
  ,&GUI_FontYaHei28_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei28_Prop4 = {
   0x5927 /* first character */
  ,0x5927 /* last character  */
  ,&GUI_FontYaHei28_CharInfo[  3] /* address of first character */
  ,&GUI_FontYaHei28_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei28_Prop3 = {
   0x5357 /* first character */
  ,0x5357 /* last character  */
  ,&GUI_FontYaHei28_CharInfo[  2] /* address of first character */
  ,&GUI_FontYaHei28_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei28_Prop2 = {
   0x4EAC /* first character */
  ,0x4EAC /* last character  */
  ,&GUI_FontYaHei28_CharInfo[  1] /* address of first character */
  ,&GUI_FontYaHei28_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei28_Prop1 = {
   0x4E1A /* first character */
  ,0x4E1A /* last character  */
  ,&GUI_FontYaHei28_CharInfo[  0] /* address of first character */
  ,&GUI_FontYaHei28_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontYaHei28 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,28 /* height of font  */
  ,28 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontYaHei28_Prop1}
  ,22 /* Baseline */
  ,11 /* Height of lowercase characters */
  ,16 /* Height of capital characters */
};

